name: ItemCooker
version: 1.3.0
main: loyfael.Main
api-version: 1.21
description: Conçu et codé par Loyfael. Plugin pour un /furnace.
commands:
  furnace:
    usage: /furnace
    description: Open the cooker inventory.
    permission: itemcooker.use
    permission-message: Vous n'avez pas la permission d'utiliser cette commande.
permissions:
  itemcooker.use:
    description: Allows the player to use the /furnace command.
    default: op
